FROM python:3.12-alpine

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update && \
  apk upgrade --no-cache && \
  apk add poppler-utils

COPY . .

RUN pip install --upgrade pip && \
  pip install -r requirements.txt && \
  python manage.py makemigrations && python manage.py migrate
EXPOSE 8000

CMD ["gunicorn", "--config", "gunicorn_config.py", "pdfer.wsgi:application"] 
